version: '3.8'

services:
  portfolio-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount SSL certificates directory
      - ./ssl:/app/ssl:rw
      # Mount database directory for persistence
      - ./data:/app/data:rw
      # Mount uploads directory
      - ./uploads:/app/uploads:rw
      # Mount logs directory
      - ./logs:/app/logs:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - SSL_CERT_PASSWORD=${SSL_CERT_PASSWORD:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      # Let's Encrypt settings
      - LETSENCRYPT_DOMAINS=${LETSENCRYPT_DOMAINS:-localhost}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-admin@localhost}
      - USE_LETS_ENCRYPT=${USE_LETS_ENCRYPT:-false}
    networks:
      - portfolio-network
    depends_on:
      - nginx-proxy
    labels:
      # Traefik labels for automatic HTTPS
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - portfolio-network
    depends_on:
      - portfolio-backend

  # Optional: Traefik reverse proxy for automatic SSL
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "8888:80"
      - "8889:443"
      - "8080:8080" # Traefik dashboard
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL:-admin@localhost}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/acme
    networks:
      - portfolio-network
    profiles:
      - traefik

networks:
  portfolio-network:
    driver: bridge

volumes:
  portfolio-ssl:
    driver: local
  portfolio-data:
    driver: local
  portfolio-uploads:
    driver: local
