name: Deploy to Azure App Service

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: codenex-app    # Set this to your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore CodeNex.csproj
    
    - name: Build
      run: dotnet build CodeNex.csproj -c Release --no-restore
    
    - name: Run tests
      run: dotnet test CodeNex.csproj -c Release --no-build --verbosity normal
      continue-on-error: true  # Continue even if tests fail (remove if you have tests)
    
    - name: Publish
      run: dotnet publish CodeNex.csproj -c Release -o ./publish --no-build
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
    
    - name: Health Check
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health || echo "Health check failed"
