name: Deploy ASP.NET Core to Azure App Service

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: 'your-webapp-name'    # Replace with your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: './PortfolioBackend'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/PortfolioBackend.csproj

    - name: Build
      run: dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/PortfolioBackend.csproj --configuration Release --no-restore

    - name: Test (if you have tests)
      run: dotnet test ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/PortfolioBackend.csproj --no-restore --verbosity normal
      continue-on-error: true  # Remove this line if you want tests to be required

    - name: Publish
      run: dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/PortfolioBackend.csproj --configuration Release --no-build --output ./publish

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ./publish

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'  # Optional: use 'staging' for staging slot
        package: ./publish
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
